// Mocks generated by Mockito 5.4.6 from annotations
// in lager_app/test/mocks/sync_service_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:lager_app/models/artikel_model.dart' as _i10;
import 'package:lager_app/screens/conflict_resolution_screen.dart' as _i9;
import 'package:lager_app/services/artikel_db_service.dart' as _i11;
import 'package:lager_app/services/nextcloud_client.dart' as _i12;
import 'package:lager_app/services/sync_error_recovery.dart' as _i4;
import 'package:lager_app/services/sync_progress_service.dart' as _i3;
import 'package:lager_app/services/sync_service.dart' as _i5;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncProgressService_1 extends _i1.SmartFake
    implements _i3.SyncProgressService {
  _FakeSyncProgressService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncErrorRecoveryService_2 extends _i1.SmartFake
    implements _i4.SyncErrorRecoveryService {
  _FakeSyncErrorRecoveryService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_3 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_4 extends _i1.SmartFake implements _i6.Database {
  _FakeDatabase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_5 extends _i1.SmartFake implements Uri {
  _FakeUri_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i5.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i3.SyncProgressService get progressService => (super.noSuchMethod(
        Invocation.getter(#progressService),
        returnValue: _FakeSyncProgressService_1(
          this,
          Invocation.getter(#progressService),
        ),
      ) as _i3.SyncProgressService);

  @override
  _i4.SyncErrorRecoveryService get errorRecoveryService => (super.noSuchMethod(
        Invocation.getter(#errorRecoveryService),
        returnValue: _FakeSyncErrorRecoveryService_2(
          this,
          Invocation.getter(#errorRecoveryService),
        ),
      ) as _i4.SyncErrorRecoveryService);

  @override
  _i7.Future<String> getDeviceId() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceId,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDeviceId,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<bool> testAndInitialize() => (super.noSuchMethod(
        Invocation.method(
          #testAndInitialize,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i5.SyncResult> syncOnce() => (super.noSuchMethod(
        Invocation.method(
          #syncOnce,
          [],
        ),
        returnValue: _i7.Future<_i5.SyncResult>.value(_FakeSyncResult_3(
          this,
          Invocation.method(
            #syncOnce,
            [],
          ),
        )),
      ) as _i7.Future<_i5.SyncResult>);

  @override
  _i7.Future<List<_i9.ConflictData>> detectConflicts() => (super.noSuchMethod(
        Invocation.method(
          #detectConflicts,
          [],
        ),
        returnValue:
            _i7.Future<List<_i9.ConflictData>>.value(<_i9.ConflictData>[]),
      ) as _i7.Future<List<_i9.ConflictData>>);

  @override
  _i7.Future<Map<String, dynamic>> syncWithConflictResolution() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithConflictResolution,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> applyConflictResolution(
    _i9.ConflictData? conflict,
    _i9.ConflictResolution? resolution, {
    _i10.Artikel? mergedVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyConflictResolution,
          [
            conflict,
            resolution,
          ],
          {#mergedVersion: mergedVersion},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> syncAttachments() => (super.noSuchMethod(
        Invocation.method(
          #syncAttachments,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [ArtikelDbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArtikelDbService extends _i1.Mock implements _i11.ArtikelDbService {
  MockArtikelDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i6.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i7.Future<_i6.Database>.value(_FakeDatabase_4(
          this,
          Invocation.getter(#database),
        )),
      ) as _i7.Future<_i6.Database>);

  @override
  _i7.Future<int> insertArtikel(_i10.Artikel? artikel) => (super.noSuchMethod(
        Invocation.method(
          #insertArtikel,
          [artikel],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i10.Artikel>> getAlleArtikel({
    int? limit = 500,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlleArtikel,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i7.Future<List<_i10.Artikel>>.value(<_i10.Artikel>[]),
      ) as _i7.Future<List<_i10.Artikel>>);

  @override
  _i7.Future<void> updateArtikel(_i10.Artikel? artikel) => (super.noSuchMethod(
        Invocation.method(
          #updateArtikel,
          [artikel],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteArtikel(_i10.Artikel? artikel) => (super.noSuchMethod(
        Invocation.method(
          #deleteArtikel,
          [artikel],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> updateBildPfad(
    int? artikelId,
    String? bildPfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBildPfad,
          [
            artikelId,
            bildPfad,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateRemoteBildPfad(
    int? artikelId,
    String? remotePfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRemoteBildPfad,
          [
            artikelId,
            remotePfad,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> setBildPfadByUuid(
    String? uuid,
    String? bildPfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBildPfadByUuid,
          [
            uuid,
            bildPfad,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setThumbnailPfadByUuid(
    String? uuid,
    String? thumbnailPfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThumbnailPfadByUuid,
          [
            uuid,
            thumbnailPfad,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setThumbnailEtagByUuid(
    String? uuid,
    String? thumbnailEtag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThumbnailEtagByUuid,
          [
            uuid,
            thumbnailEtag,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setBildPfadByUuidSilent(
    String? uuid,
    String? bildPfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBildPfadByUuidSilent,
          [
            uuid,
            bildPfad,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setRemoteBildPfadByUuid(
    String? uuid,
    String? remoteBildPfad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRemoteBildPfadByUuid,
          [
            uuid,
            remoteBildPfad,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i10.Artikel?> getArtikelByUUID(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtikelByUUID,
          [uuid],
        ),
        returnValue: _i7.Future<_i10.Artikel?>.value(),
      ) as _i7.Future<_i10.Artikel?>);

  @override
  _i7.Future<_i10.Artikel?> getArtikelByRemotePath(String? remotePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtikelByRemotePath,
          [remotePath],
        ),
        returnValue: _i7.Future<_i10.Artikel?>.value(),
      ) as _i7.Future<_i10.Artikel?>);

  @override
  _i7.Future<List<_i10.Artikel>> getUnsyncedArtikel() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedArtikel,
          [],
        ),
        returnValue: _i7.Future<List<_i10.Artikel>>.value(<_i10.Artikel>[]),
      ) as _i7.Future<List<_i10.Artikel>>);

  @override
  _i7.Future<List<_i10.Artikel>> getPendingChanges() => (super.noSuchMethod(
        Invocation.method(
          #getPendingChanges,
          [],
        ),
        returnValue: _i7.Future<List<_i10.Artikel>>.value(<_i10.Artikel>[]),
      ) as _i7.Future<List<_i10.Artikel>>);

  @override
  _i7.Future<void> markSynced(
    String? uuid,
    String? etag, {
    String? remotePath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [
            uuid,
            etag,
          ],
          {#remotePath: remotePath},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> upsertArtikel(
    _i10.Artikel? artikel, {
    String? etag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertArtikel,
          [artikel],
          {#etag: etag},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> upsertFromRemote(
    String? remotePath,
    String? etag,
    String? jsonBody,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertFromRemote,
          [
            remotePath,
            etag,
            jsonBody,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setLastSyncTime() => (super.noSuchMethod(
        Invocation.method(
          #setLastSyncTime,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> getLastSyncTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastSyncTime,
          [],
        ),
        returnValue: _i7.Future<DateTime?>.value(),
      ) as _i7.Future<DateTime?>);

  @override
  _i7.Future<void> openDatabase() => (super.noSuchMethod(
        Invocation.method(
          #openDatabase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markAsModified(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markAsModified,
          [uuid],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markForForceLocal(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markForForceLocal,
          [uuid],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markForForceMerge(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #markForForceMerge,
          [uuid],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearPendingResolution(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #clearPendingResolution,
          [uuid],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.Artikel>> searchArtikel(
    String? query, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArtikel,
          [query],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i10.Artikel>>.value(<_i10.Artikel>[]),
      ) as _i7.Future<List<_i10.Artikel>>);

  @override
  _i7.Future<bool> existsKombination({
    required String? name,
    required String? ort,
    required String? fach,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsKombination,
          [],
          {
            #name: name,
            #ort: ort,
            #fach: fach,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> existsArtikelnummer(int? nummer) => (super.noSuchMethod(
        Invocation.method(
          #existsArtikelnummer,
          [nummer],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> resetDatabase({int? startId = 1000}) => (super.noSuchMethod(
        Invocation.method(
          #resetDatabase,
          [],
          {#startId: startId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAlleArtikel() => (super.noSuchMethod(
        Invocation.method(
          #deleteAlleArtikel,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> insertArtikelList(List<_i10.Artikel>? artikelList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertArtikelList,
          [artikelList],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isDatabaseEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isDatabaseEmpty,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> getNextArtikelNummer() => (super.noSuchMethod(
        Invocation.method(
          #getNextArtikelNummer,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int?> getMaxArtikelnummer() => (super.noSuchMethod(
        Invocation.method(
          #getMaxArtikelnummer,
          [],
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);

  @override
  _i7.Future<void> closeDatabase() => (super.noSuchMethod(
        Invocation.method(
          #closeDatabase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> injectDatabase(_i6.Database? db) => (super.noSuchMethod(
        Invocation.method(
          #injectDatabase,
          [db],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [NextcloudClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNextcloudClient extends _i1.Mock implements _i12.NextcloudClient {
  MockNextcloudClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Uri get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _FakeUri_5(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as Uri);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  _i7.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> createFolder(String? path) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [path],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i12.RemoteItemMeta>> listItemsEtags(
          {String? folderPath = 'items/'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listItemsEtags,
          [],
          {#folderPath: folderPath},
        ),
        returnValue: _i7.Future<List<_i12.RemoteItemMeta>>.value(
            <_i12.RemoteItemMeta>[]),
      ) as _i7.Future<List<_i12.RemoteItemMeta>>);

  @override
  _i7.Future<String> downloadItem(String? path) => (super.noSuchMethod(
        Invocation.method(
          #downloadItem,
          [path],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #downloadItem,
            [path],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String?> uploadItem(
    String? path,
    String? body, {
    String? ifMatch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadItem,
          [
            path,
            body,
          ],
          {#ifMatch: ifMatch},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> deleteItem(String? path) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [path],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String?> uploadAttachment(
    String? itemUUID,
    String? filename,
    List<int>? data, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAttachment,
          [
            itemUUID,
            filename,
            data,
          ],
          {#contentType: contentType},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<List<int>> downloadAttachment(
    String? itemUUID,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAttachment,
          [
            itemUUID,
            filename,
          ],
        ),
        returnValue: _i7.Future<List<int>>.value(<int>[]),
      ) as _i7.Future<List<int>>);
}
