#//pubspec.yaml

#//🔧 Hinweise zur WebDAV-Nutzung
#//Das Paket webdav_client erlaubt dir den Zugriff auf WebDAV-Server wie Nextcloud.
#//Hoch- und Herunterladen von Dateien (z. B. JSON, Bilder)
#//Verzeichnisverwaltung

name: elektronik_verwaltung
description: Eine App zur Verwaltung von Elektronik- und Bastelartikel
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  image_picker: ^1.2.0
  image_picker_for_web: ^3.1.0
#  flutter_barcode_scanner: ^2.0.0
  provider: ^6.0.3
  intl: ^0.17.0
  file_picker: ^10.1.0
  pdf: ^3.8.1
  printing: ^5.9.0
  flutter_local_notifications: ^19.4.1
  http: ^1.2.2
  webdav_client: ^1.0.0 # Paket für WebDAV/Nextcloud
  flutter_secure_storage: ^9.2.2
  mime: ^1.0.5
  path: ^1.9.0
  logger: ^2.0.2
  mobile_scanner: ^3.5.0
  #device_info_plus: ^10.1.0
  camera: ^0.11.0+1
  sqflite_common_ffi: ^2.3.6
  

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    