#//pubspec.yaml

name: elektronik_verwaltung
description: Eine App zur Verwaltung von Elektronik- und Bastelartikel
version: 1.3.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  image_picker: ^1.2.0
  image_picker_for_web: ^3.1.0
  provider: ^6.0.3
  intl: ^0.20.2
  file_picker: ^10.1.0
  pdf: ^3.8.1
  printing: ^5.9.0
  flutter_local_notifications: ^19.4.1
  http: ^1.2.2
  webdav_client: ^1.0.0
  flutter_secure_storage: ^9.2.2
  mime: ^2.0.0
  path: ^1.9.0
  logger: ^2.0.2
  mobile_scanner: ^7.0.1
  #device_info_plus: ^10.1.0
  camera: ^0.11.0+1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  sqflite_common_ffi: ^2.3.6
  csv: ^6.0.0
  test_api: ^0.7.6
  archive: ^4.0.7
  

  connectivity_plus: ^5.0.2 # Für WLAN-Check (nur Android/iOS)

  

dev_dependencies:
  mockito: ^5.4.2
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  file_selector: ^1.0.4
  file_selector_platform_interface: any
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#1976d2"
  image: assets/images/app_logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  image_path: assets/images/app_logo.png
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256  