name: lagerverwaltung
description: Private Lagerverwaltung für Elektronik/Basteln (Android)
publish_to: 'none'
version: 1.0.0+1


environment:
sdk: ">=3.3.0 <4.0.0"


dependencies:
flutter:
sdk: flutter
sqflite: ^2.3.3
path: ^1.9.0
path_provider: ^2.1.4
intl: ^0.19.0
pdf: ^3.10.8
printing: ^5.13.4
share_plus: ^10.0.2
barcode: ^2.2.5


flutter:
uses-material-design: true
